#!/usr/bin/env bash
# StreetSentinel one-line installer.
#   curl -fsSL https://get.streetsentinel.app/install.sh | sudo bash
# Idempotent: re-running never regenerates existing secrets, so it doubles as a
# safe repair/update command.
#
# Optional (future private images): pass a GHCR token to docker login before pull:
#   curl -fsSL https://get.streetsentinel.app/install.sh | sudo bash -s -- --token GHCR_PAT
# Default behavior pulls PUBLIC images (no login needed).
set -euo pipefail

# --- Config ---------------------------------------------------------------
INSTALL_DIR="${INSTALL_DIR:-/opt/streetsentinel}"
# Base URL the installer fetches docker-compose.yml + .env.example from.
# Default = this public streetsentinel-deploy repo's raw files (works with no
# extra setup). Override with DEPLOY_BASE_URL=... to use a branded host
# (e.g. https://get.streetsentinel.app once Cloudflare Pages is pointed here).
DEPLOY_BASE_URL="${DEPLOY_BASE_URL:-https://raw.githubusercontent.com/Delingr-cmd/streetsentinel-deploy/main}"
GHCR_TOKEN=""
GHCR_USER="${GHCR_USER:-delingr-cmd}"

# --- Helpers --------------------------------------------------------------
RED=$'\e[31m'; GRN=$'\e[32m'; YEL=$'\e[33m'; BLU=$'\e[34m'; RST=$'\e[0m'
step() { echo; echo "${BLU}==> $*${RST}"; }
ok()   { echo "${GRN}    ok ${RST}$*"; }
warn() { echo "${YEL}    ! ${RST}$*"; }
fail() { echo "${RED}    x ${RST}$*" >&2; exit 1; }
have() { command -v "$1" >/dev/null 2>&1; }

# --- Parse args -----------------------------------------------------------
while [ $# -gt 0 ]; do
  case "$1" in
    --token) GHCR_TOKEN="${2:-}"; shift 2 ;;
    --token=*) GHCR_TOKEN="${1#*=}"; shift ;;
    --dir) INSTALL_DIR="${2:?}"; shift 2 ;;
    *) warn "ignoring unknown argument: $1"; shift ;;
  esac
done

# --- Root check -----------------------------------------------------------
if [ "$(id -u)" -ne 0 ]; then
  fail "Run with sudo: curl -fsSL ${DEPLOY_BASE_URL}/install.sh | sudo bash"
fi

# --- Detect OS / arch -----------------------------------------------------
step "Detecting platform"
OS="$(uname -s)"
ARCH="$(uname -m)"
if [ "$OS" != "Linux" ]; then
  fail "This installer supports Linux only (detected: $OS). For Windows use install.ps1."
fi
case "$ARCH" in
  x86_64|amd64|aarch64|arm64) ok "OS=$OS ARCH=$ARCH" ;;
  *) warn "unrecognized arch $ARCH — continuing, Docker may not have images" ;;
esac
if [ -r /etc/os-release ]; then
  # shellcheck disable=SC1091
  . /etc/os-release
  ok "Distro: ${PRETTY_NAME:-unknown}"
fi

# --- Install Docker Engine + Compose plugin if missing --------------------
step "Ensuring Docker is installed"
if have docker && docker compose version >/dev/null 2>&1; then
  ok "Docker + Compose plugin already present"
else
  warn "Installing Docker via get.docker.com convenience script"
  curl -fsSL https://get.docker.com | sh
  systemctl enable --now docker >/dev/null 2>&1 || true
  if ! docker compose version >/dev/null 2>&1; then
    fail "Docker Compose plugin not available after install. Install docker-compose-plugin manually."
  fi
  ok "Docker installed"
fi

# --- Optional GHCR login (private-image path) -----------------------------
if [ -n "$GHCR_TOKEN" ]; then
  step "Logging in to GHCR (private images)"
  echo "$GHCR_TOKEN" | docker login ghcr.io -u "$GHCR_USER" --password-stdin \
    && ok "GHCR login ok" || fail "GHCR login failed"
else
  ok "Using public images (no GHCR login)"
fi

# --- Install dir + fetch compose/env --------------------------------------
step "Preparing $INSTALL_DIR"
mkdir -p "$INSTALL_DIR"
cd "$INSTALL_DIR"

fetch() {
  # $1 = remote filename, $2 = local filename
  curl -fsSL "${DEPLOY_BASE_URL}/$1" -o "$2" \
    || fail "Failed to fetch ${DEPLOY_BASE_URL}/$1"
}
fetch docker-compose.yml docker-compose.yml
ok "Fetched docker-compose.yml"
if [ ! -f .env.example ]; then
  fetch .env.example .env.example
  ok "Fetched .env.example"
fi

# --- Generate bootstrap secrets into .env (only if absent) ----------------
step "Bootstrapping .env"
if [ -f .env ]; then
  ok ".env already exists — leaving secrets untouched (idempotent)"
else
  have openssl || fail "openssl is required to generate secrets"
  SECRET_KEY_VAL="$(openssl rand -hex 32)"
  CRED_KEY_VAL="$(openssl rand -hex 32)"
  WEBHOOK_VAL="$(openssl rand -hex 32)"
  FTP_PASS_VAL="$(openssl rand -base64 36 | tr -d '/+=' | cut -c1-32)"
  PG_PASS_VAL="$(openssl rand -base64 36 | tr -d '/+=' | cut -c1-32)"
  cat > .env <<EOF
# Generated by install.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ). Do not edit by hand.
SECRET_KEY=${SECRET_KEY_VAL}
CREDENTIAL_ENCRYPTION_KEY=${CRED_KEY_VAL}
WEBHOOK_SECRET=${WEBHOOK_VAL}
POSTGRES_PASSWORD=${PG_PASS_VAL}
DATABASE_URL=postgresql+asyncpg://cctv:${PG_PASS_VAL}@postgres:5432/cctv_platform
INSTANCE_ROLE=active
PORT=8000
TUNNEL_TOKEN_PATH=/config/tunnel/token
FTP_ENABLED=true
FTP_PORT=2121
FTP_PASSWORD=${FTP_PASS_VAL}
FTP_PASSIVE_PORT_START=60000
FTP_PASSIVE_PORT_END=60100
EOF
  chmod 600 .env
  ok "Generated fresh bootstrap secrets in .env"
fi

# --- Pull + up ------------------------------------------------------------
step "Pulling images and starting the stack"
docker compose pull || warn "pull failed for some images (will build/use cache)"
docker compose up -d
ok "Stack started"

# --- Wait for health ------------------------------------------------------
step "Waiting for the app to become healthy"
PORT_VAL="$(grep -E '^PORT=' .env | cut -d= -f2)"
PORT_VAL="${PORT_VAL:-8000}"
HEALTHY=0
for _ in $(seq 1 60); do
  if curl -fsS "http://localhost:${PORT_VAL}/healthz" >/dev/null 2>&1; then
    HEALTHY=1
    break
  fi
  sleep 3
done
if [ "$HEALTHY" -eq 1 ]; then
  ok "App is healthy"
else
  warn "App did not report healthy within ~3 min. Check: docker compose logs app"
fi

# --- Print LAN URL --------------------------------------------------------
SERVER_IP="$(hostname -I 2>/dev/null | awk '{print $1}')"
step "Done"
echo
echo "  ${GRN}Open http://${SERVER_IP:-<server-ip>}:${PORT_VAL} to finish setup.${RST}"
echo
echo "  Logs:    docker compose -f ${INSTALL_DIR}/docker-compose.yml logs -f app"
echo "  Update:  cd ${INSTALL_DIR} && docker compose pull && docker compose up -d"
echo "  WhatsApp escalation (optional): docker compose --profile whatsapp up -d"
echo
